# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('equation', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=250)),
            ],
        ),
    ]
